### ISSUE TITLE
Advanced settings

### ISSUE THREAD

**Issue by squidy** [bryangerlach/rdgen#4]
Hi.. Is there a way to set advanced settings using rdgen, like hide-tray, disable IDs book , etc?

**Comment by bryangerlach** [comment]
You should be able to set any of the advanced settings from [here](https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/) by putting them in the Other section. Default if you want to set the value as default, but allow the user to change, or Override if you need to set the value and not allow it to be changed by the user. So you will input stuff like this:

`hide-tray=Y`

with one setting per line.
